name: Check membership
inputs:
  organization-name:
    required: true
  member-name:
    required: true
  token:
    required: true
outputs:
  check-result:
    description: Membership check result
    value: ${{ steps.membership-check.outputs.check-result }}
runs:
  using: composite
  steps:
    - id: membership-check
      shell: bash
      run: |-
        output=$(gh api "orgs/${{ inputs.organization-name }}/members/${{ inputs.member-name }}")
        status=$?

        echo "::debug::${output}"

        if [[ ${status} -ne 0 ]] ; then
          echo "::set-output name=check-result::false"
        else
          echo "::set-output name=check-result::true"
        fi
      env:
        GH_TOKEN: ${{ inputs.token }}
