name: "Create Jira issue"
description: "Create Jira Issue"
inputs:
  JIRA_BASE_URL:
    description: 'JIRA BASE URL'
    required: true
  JIRA_USER_EMAIL:
    description: 'JIRA USER EMAIL'
    required: true
  JIRA_API_TOKEN:
    description: 'JIRA API TOKEN'
    required: true
  TARGET_JIRA_PROJECT:
    description: 'Enter the JIRA Project key'
    required: true
  JIRA_LABEL:
    description: 'Specify the label you want to put on JIRA side'
    required: false

runs:
  using: "composite"
  steps:
    - name: Jira Login
      id: login
      uses: atlassian/gajira-login@v2.0.0
      env:
        JIRA_BASE_URL: ${{ inputs.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ inputs.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ inputs.JIRA_API_TOKEN }}
        

    - name: Create Jira issue
      id: create_jira_issue
      uses: atlassian/gajira-create@v2.0.1
      with:
        project: ${{ inputs.TARGET_JIRA_PROJECT }}
        issuetype: Task
        summary: |
           ${{ github.event.issue.title }} [GH#${{ github.event.issue.number }}]
        description: |
          {panel}
          *Created By:* ${{ github.event.issue.user.login }}
          [Github permalink|${{ github.event.issue.html_url }}]
          {panel}
        fields: '{"labels": ["${{ inputs.JIRA_LABEL }}"]}'

    - name: Update title of GitHub issue
      uses: actions/github-script@v4.0.2
      with:
        script: |
          const newTitle = `${{ github.event.issue.title }} [${{ steps.create_jira_issue.outputs.issue }}]`
          github.issues.update({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: newTitle
          })
    - name: Add comment to GitHub issue
      uses: actions/github-script@v4.0.2
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Internal Jira issue: [${{ steps.create_jira_issue.outputs.issue }}](${{ inputs.JIRA_BASE_URL }}/browse/${{ steps.create_jira_issue.outputs.issue }})'
          })
