name: Jira Sync
on:
  issues:
    types: [opened, labeled, unlabeled]
  issue_comment:
    types: [created]
jobs:
  sync:
    name: Sync Items
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: mheap/github-action-issue-to-jira@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          JIRA_HOST: ${{ secrets.JIRA_HOST }}
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }} # See https://id.atlassian.com/manage/api-tokens
          project: DEG
          assignee: ayberk@hazelcast.com
