on:
  issues:
    types: [opened]

name: Test Create Issue

jobs:
  build:
    runs-on: ubuntu-latest
    name: Create Issue
    steps:
     - name: Checkout
       uses: actions/checkout@master
      
     - name: Login
       uses: atlassian/gajira-login@master
       env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        
     - name: Create
       id: create
       uses: atlassian/gajira-create@master
       with:
         project: DEG
         issuetype: Task
         summary: | 
          [GH-${{ github.event.issue.number }}] ${{ github.event.issue.title }}
         description: |
          *URL:* ${{ github.event.issue.html_url }}
          *Created By:* ${{ github.event.issue.user.login }}
          ${{ github.event.issue.body }}
