name: Create Issue in Jira when to-jira label added

on:
  issues:
    types: labeled

const labels = ${{ github.event.issue.labels }}

if(labels.find(label => contains(github.event.issue.labels.*.name, 'Team: '))) {
              
              uses: actions/github-script@0.9.0
              with:
              script: |
              const team_label = github.event.issue.labels.*.name.split('Team: ')[1]
              return team_label
            } else {
              return null
            }


jobs:
  jira1:
    if: ${{ github.event.label.name == 'to-jira' }}
    runs-on: ubuntu-latest
    steps:
      - name: Test composite one
        uses: hazelcast/github-jira-tool-action@v2
        with:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          TARGET_JIRA_PROJECT: DEG
          JIRA_LABEL: from-gh
  jira2:
    if: ${{ github.event.label.name == 'to-client-jira' }}
    runs-on: ubuntu-latest
    steps:
      - name: Test composite one
        uses: hazelcast/github-jira-tool-action@main
        with:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          TARGET_JIRA_PROJECT: DEG
          JIRA_LABEL: Java","Team
          ISSUE_TYPE: Bug
