name: Create Issue in Jira when to-jira label added

on:
  issues:
    types: labeled

jobs:
  jira0:
    if: contains(github.event.issue.labels.*.name, 'Team')
    runs-on: ubuntu-latest
    steps:
      - name: Capture Team Label
        env: 
          TEAM_LABEL: ${{ toJson(github.event.issue.labels) }}.find(label => contains(github.event.issue.labels.*.name, 'Team')))
        uses: actions/github-script@0.9.0
        with:
          script: |
            echo $TEAM_LABEL.split('Team: ')[0] >> $GITHUB_OUTPUT
        id: team_label
        
  jira00:
    runs-on: ubuntu-latest
    steps:
      - name: Check if GitHub Issue has JIRA_ISSUE_LABEL
        if: contains(github.event.issue.labels.*.name, 'Team')
        id: 00_team_label
      - uses: actions/github-script@v2.0.0
      - uses: actions/github-script@0.9.0
        env:
          TEAM_LABEL: ${{ secrets.JIRA_ISSUE_LABEL }}
        with:
          result-encoding: string
          script: |
            const labels = ${{ toJson(github.event.issue.labels) }}
            if(labels.find(label => label.name == "Team:**")) {
              return echo $TEAM_LABEL.split('Team: ')[0] >> $GITHUB_OUTPUT
            }
  
  jira1:
    if: ${{ github.event.label.name == 'to-jira' }}
    runs-on: ubuntu-latest
    steps:
      - name: Test composite one
        uses: hazelcast/github-jira-tool-action@v2
        with:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          TARGET_JIRA_PROJECT: DEG
          JIRA_LABEL: from-gh
  jira2:
    if: ${{ github.event.label.name == 'to-client-jira' }}
    runs-on: ubuntu-latest
    steps:
      - name: Test composite one
        uses: hazelcast/github-jira-tool-action@main
        with:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          TARGET_JIRA_PROJECT: DEG
          JIRA_LABEL: Java","${{steps.00_team_label.outputs[0]}}
          ISSUE_TYPE: Bug
