on:
  issues:
    types: [opened]

name: Test Create Issue

jobs:
  build:
    runs-on: ubuntu-latest
    name: Create Issue
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create
      id: create
      uses: ./
      with:
        project: DEG
        issuetype: Story
        summary: |
          github.event.issue.title
        description: |
          github.event.issue.body
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
